site_name: 5CORE
site_url: https://github.com/debsify
site_author: Debsify Satisfying
site_description: we love 
theme:
  name: material
  font:
    text: Open Sans
    code: Noto Sans
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    #palette
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: deep orange
        accent: orange
        toggle:
          icon: material/brightness-7
          name: Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: deep orange
        accent: orange
        toggle:
          icon: material/brightness-4
          name: Light mode
  
  features:
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.instant.progress
      # - navigation.instant.preview
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.path
      # - navigation.prune
      - navigation.indexes
      - toc.follow
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - search.share
      - header.autohide
      - announce.dismiss
      - navigation.footer
      - content.action.edit
      - content.action.view

repo_name: debsify/fivecore
repo_url: https://github.com/debsify/fivecore
edit_uri: edit/main/docs

extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/debsify
        name: Debsify Satisfying
  alternate:
      - name: English
        link: /en/ 
        lang: en
      - name: Indonesian
        link: /id/
        lang: id

plugins:
    - search

copyright: Copyright &copy; 2024 Debsify Satisfying