[tool.poetry]
name = "fivecore"
version = "0.1.0"
description = "Deskripsi singkat proyek Anda"
authors = ["Nama Anda <email_anda@contoh.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23"
pandas = "^1.5"
