name: ci
on:
    push:
        branches:
            - main
            - master

env:
  PYTHON_VERSION: 3.x

permissions:
    contents: write
    id-token: write
    pages: write


jobs:
  documentation:
    name: build documentation
    runs-on: ubuntu-latest
    steps:
        - name: Setup actions checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            sparse-checkout: |
                docs
                includes
                material/overrides
                src/templates/partials/languages

        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}
            cache: pip
            cache-dependency-path: |
              requirements.txt
              pyproject.toml
        - name: Set up build cache
          uses: actions/cache/restore@v4
          with:
            key: mkdocs-material-${{ hashfiles('.cache/**') }}
            path: .cache
            restore-keys: |
              mkdocs-material-
        - name: Set up Depend
          run: sudo apt-get install pngquant

        - name: Install Python dependencies
          run: |
            pip install mkdocs-material
            pip install .[recommended,git,imaging]

        - name: Upload to GitHub Pages
          uses: actions/upload-pages-artifact@v3
          with:
            path: site

        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4

        - name: Save build cache
          uses: actions/cache/save@v4
          with:
             key: mkdocs-material-${{ hashfiles('.cache/**') }}
             path: .cache