name: ci
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x
  NODE_VERSION: 20.x

permissions:
    contents: write


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: apt-get install pngquant
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
